config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, skip: [:registrations, :passwords]

  devise_scope :customer do
    root 'devise/sessions#new'
  end

  authenticate :customer do
    resources :customer_accounts, only: [:index, :show] do
      member do
        get :new_enrolment
        put :enroll
      end
      resources :rewards, only: [:new, :create]
      resources :purchases, only: [:new, :create]
    end
  end

end

app/models/brand.rb
class Brand < ActiveRecord::Base

  has_many :reward_programs, inverse_of: :brand, dependent: :destroy
  has_many :customer_accounts, inverse_of: :brand, dependent: :destroy
  has_many :customers, through: :customer_accounts
  has_many :rewards, through: :customer_accounts
  has_many :purchases, through: :customer_accounts

  validates               :name, :account_id, :secret_key, presence: true
  validates_uniqueness_of :account_id
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :customer_accounts, inverse_of: :customer, dependent: :destroy
  has_many :brands, through: :customer_accounts
  has_many :rewards, through: :customer_accounts
  has_many :purchases, through: :customer_accounts
  has_many :reward_programs, through: :customer_accounts
end

app/models/customer_account.rb
class CustomerAccount < ActiveRecord::Base

  paginates_per 10

  belongs_to :customer, inverse_of: :customer_accounts
  belongs_to :brand, inverse_of: :customer_accounts
  belongs_to :reward_program, inverse_of: :customer_accounts
  has_many   :rewards, inverse_of: :customer_account, dependent: :destroy
  has_many   :purchases, inverse_of: :customer_account, dependent: :destroy

  validates               :customer, :brand, presence: true
  validates_uniqueness_of :customer, scope: :brand
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base

  belongs_to :customer_account, inverse_of: :rewards

  after_save :process_purchase, if: :amount_changed?

  validates :amount, :customer_account, presence: true
  validates :amount, numericality: { only_integer: true, greater_than: 0 }, allow_blank: true

private

  def process_purchase
    value = amount - amount_was
    customer_account.total_purchases += value
    if program = customer_account.reward_program
      customer_account.points_balance += program.points_dollar * value
    end
    customer_account.save
  end
end

app/models/reward.rb
class Reward < ActiveRecord::Base

  belongs_to :customer_account, inverse_of: :rewards

  after_save :process_reward, if: :points_changed?

  validates :points, :customer_account, presence: true
  validates :points, numericality: { only_integer: true, greater_than: 0 }, allow_blank: true
  validate  :check_balance, if: :points_changed?

private

  def check_balance
    value = points - points_was

    if customer_account.points_balance < 100
      errors.add(:points, "can't redeem when balance is less than 100")
    elsif customer_account.points_balance < value
      errors.add(:points, "can't be greater than balance")
    end
  end

  def process_reward
    value = points - points_was
    customer_account.points_balance -= value
    customer_account.save
  end
end

app/models/reward_program.rb
class RewardProgram < ActiveRecord::Base

  belongs_to :brand, inverse_of: :reward_programs
  has_many   :customer_accounts, inverse_of: :reward_program, dependent: :nullify
  has_many   :customers, through: :customer_accounts

  validates :brand, :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    customer_accounts_path
  end
end

app/controllers/concerns/authorize_customer.rb
module AuthorizeCustomer
  extend ActiveSupport::Concern

private

  def load_and_authorize(args = {})
    args[:resources] ||= controller_name
    resource = args[:resources].singularize
    klass = args[:resources].classify.constantize
    args[:inst_var] ||= resource
    args[:redirect_url] ||= customer_accounts_path
    args[:customer_id] ||= :customer_id

    instance_variable_set("@#{args[:inst_var]}", klass.find(params["#{resource}_id"] || params[:id]))

    if current_customer.id != instance_variable_get("@#{args[:inst_var]}").send(args[:customer_id])
      respond_to do |format|
        format.html { redirect_to args[:redirect_url], status: :see_other }
        format.js { render js: "window.location = '#{args[:redirect_url]}'" }
      end
    end
  end
end

app/controllers/concerns/authorize_user.rb
module AuthorizeUser
  extend ActiveSupport::Concern

private

  def load_and_authorize(args = {})
    args[:resources] ||= controller_name
    resource = args[:resources].singularize
    klass = args[:resources].classify.constantize
    args[:inst_var] ||= resource
    args[:redirect_url] ||= brands_path
    args[:user_id] ||= :user_id

    instance_variable_set("@#{args[:inst_var]}", klass.find(params["#{resource}_id"] || params[:id]))

    if current_user.id != instance_variable_get("@#{args[:inst_var]}").send(args[:user_id])
      respond_to do |format|
        format.html { redirect_to args[:redirect_url], status: :see_other }
        format.js { render js: "window.location = '#{args[:redirect_url]}'" }
      end
    end
  end
end

app/controllers/customer_accounts_controller.rb
class CustomerAccountsController < ApplicationController
  include AuthorizeCustomer
  before_action :load_and_authorize, except: :index

  def index
    @accounts = current_customer.customer_accounts.page(params[:page]).includes(:brand)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @last_purchases = @customer_account.purchases.order(created_at: :desc).limit(5)
    @last_rewards   = @customer_account.rewards.order(created_at: :desc).limit(5)

    respond_to do |format|
      format.html
    end
  end

  def new_enrolment
    respond_to do |format|
      format.js
    end
  end

  def enroll
    @customer_account.reward_program = @customer_account.brand.reward_programs.find_by(id: params[:customer_account][:reward_program_id])

    respond_to do |format|
      if @customer_account.save
        format.js
      else
        format.js { render :new_enrolment }
      end
    end
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  include AuthorizeCustomer
  before_action do
    load_and_authorize(resources: 'customer_accounts')
  end

  def new
    @purchase = @customer_account.purchases.new(amount: nil)

    respond_to do |format|
      format.js
    end
  end

  def create
    @purchase = @customer_account.purchases.new(amount: params[:purchase][:amount])

    respond_to do |format|
      if @purchase.save
        @last_purchases = @customer_account.purchases.order(created_at: :desc).limit(5)
        format.js
      else
        format.js { render :new }
      end
    end
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  include AuthorizeCustomer
  before_action do
    load_and_authorize(resources: 'customer_accounts')
  end

  def new
    @reward = @customer_account.rewards.new(points: nil)

    respond_to do |format|
      format.js
    end
  end

  def create
    @reward = @customer_account.rewards.new(points: params[:reward][:points])

    respond_to do |format|
      if @reward.save
        @last_rewards   = @customer_account.rewards.order(created_at: :desc).limit(5)
        format.js
      else
        format.js { render :new }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customer_accounts/_enroll_form.html.erb
<div class="modal-wrapper">
  <div class="inner-box modal-box" style="width: 500px;">
    <div class="page-header" style="margin-top: 0;">
      <span class="h4">Reward Program</span>
    </div>
    <%= form_for account, url: enroll_customer_account_path(account), html: { class: 'form-horizontal' }, method: :put, remote: true do |f| %>
      <div class="form-group required" style="margin-bottom: 20px;">
        <div class="col-sm-offset-3 col-sm-6">
          <%= f.collection_select :reward_program_id, account.brand.reward_programs, :id, :name, { prompt: true }, {class: 'form-control', autocomplete: 'false'} %>
        </div>
      </div>

      <span class="break-row"></span>

      <div class="row">
        <div class="col-sm-12" style="text-align: center;">
          <%= f.submit 'Enroll', class: 'btn btn-primary' %>
          <button type="button" class="btn btn-default" onclick="$('.modal-wrapper').remove();">Cancel</button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/customer_accounts/_list.html.erb
<div style="margin: 0 20px;">
  <% accounts.each do |account| %>
    <%= link_to customer_account_path(account) do %>
      <div class="row" style="margin-bottom: 15px; border: 1px solid #42a3db; border-radius: 2px;">
        <div class="col-sm-12">
          <h4><%= account.brand.name %></h4>
        </div>
        <div class="col-sm-12">
          <p>Points: <%= account.points_balance %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/customer_accounts/_reward_program.html.erb
<% if account.reward_program %>
  <span style="font-style: italic;"><%= account.reward_program.name %> - <%= pluralize(account.reward_program.points_dollar, 'point') %> per dollar</span>
<% else %>
  <%= link_to new_enrolment_customer_account_path(account), remote: true, class: 'btn btn-warning btn-sm', style: 'margin-left: 10px;' do %>
    <i class="glyphicon glyphicon-plus"></i> Enroll
  <% end %>
<% end %>

app/views/customer_accounts/enroll.js.erb
if ($('.modal-wrapper').length) {
  $('.modal-wrapper').remove();
}

$('#reward-program').html("<%= escape_javascript(render 'reward_program', account: @customer_account) %>");

app/views/customer_accounts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-offset-1 col-sm-10">
      <div class="inner-box">
        <div class="page-header" style="margin-top: 0;">
          <span class="h3">My Accounts <span id="account-count" class="badge" style="font-weight: normal;"><%= @accounts.total_count %></span></span>
        </div>

        <div id="accounts-list">
          <%= render 'list', accounts: @accounts %>
        </div>

        <div id="index-paginate">
          <%= paginate @accounts, remote: true %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/customer_accounts/index.js.erb
$('#account-count').html(<%= @accounts.total_count %>);
$('#accounts-list').html("<%= escape_javascript(render 'list', accounts: @accounts) %>");
$('#index-paginate').html("<%= escape_javascript(paginate(@accounts, remote: true).to_s) %>");

app/views/customer_accounts/new_enrolment.js.erb
if ($('.modal-wrapper').length) {
  $('.modal-wrapper').remove();
}

$('body').prepend("<%= escape_javascript(render 'enroll_form', account: @customer_account) %>");

app/views/customer_accounts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-offset-1 col-sm-10">
      <div class="inner-box">
        <div class="page-header" style="margin-top: 0;">
          <span class="h3"><%= @customer_account.brand.name %></span>
        </div>

        <div style="padding: 0 8px 20px;">
          <div class="row" style="font-size: 14px;">
            <div class="col-sm-7">
              Reward Program:
              <span id="reward-program">
                <%= render 'reward_program', account: @customer_account %>
              </span>
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading" style="padding-top: 3px; padding-bottom: 3px;">
            <div class="row">
              <div class="col-sm-12" style="margin: 7px auto;">
                <div class="panel-title truncate" style="display: inline-block; width: 75%; margin-top: 3px;">
                  <a data-toggle="collapse" href="#collapse_rewards" style="text-decoration: none;">
                    Points: <span id="points-balance"><%= @customer_account.points_balance %></span>
                  </a>
                </div>
                <%= link_to new_customer_account_reward_path(@customer_account), remote: true, class: 'btn btn-primary btn-sm pull-right', style: 'width: 70px;' do %>Redeem<% end %>
              </div>
            </div>
          </div>

          <div id="collapse_rewards" class="panel-collapse collapse">
            <div id="reward-list" class="panel-body" style="padding-bottom: 0;">
              <%= render 'rewards/list', rewards: @last_rewards %>
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading" style="padding-top: 3px; padding-bottom: 3px;">
            <div class="row">
              <div class="col-sm-12" style="margin: 7px auto;">
                <div class="panel-title truncate" style="display: inline-block; width: 75%; margin-top: 3px;">
                  <a data-toggle="collapse" href="#collapse_purchases" style="text-decoration: none;">
                    Purchases: <span id="total-purchases"><%= number_to_currency(@customer_account.total_purchases, precision: 0) %></span>
                  </a>
                </div>
                <%= link_to new_customer_account_purchase_path(@customer_account), remote: true, class: 'btn btn-primary btn-sm pull-right', style: 'width: 70px;' do %>Buy<% end %>
              </div>
            </div>
          </div>

          <div id="collapse_purchases" class="panel-collapse collapse">
            <div id="purchase-list" class="panel-body" style="padding-bottom: 0;">
              <%= render 'purchases/list', purchases: @last_purchases %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-site navbar-default" role="navigation" style="z-index: 1; min-height: 60px;">
  <div class="container">
    <div class="navbar-header">
      <% if customer_signed_in? %>
        <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
      <% end %>
      <%= link_to root_path, class: 'navbar-brand', style: 'line-height: 30px;' do %>
        <span class="title-light"><span class="title-primary text-primary">Loyalty</span>Plus</span>
      <% end %>
    </div>

    <% if customer_signed_in? %>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-user"></i> <%= current_customer.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu" style="border-radius: 0;">
              <li><%= link_to customer_accounts_path do %>My Accounts<% end %></li>
            </ul>
          </li>
          <li>
            <%= link_to destroy_customer_session_path, method: :delete do %><i class="glyphicon glyphicon-off"></i> Logout<% end %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>LoyaltyPlus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/navbar" %>

  <%= yield %>
</body>
</html>

app/views/purchases/_form.html.erb
<div class="modal-wrapper">
  <div class="inner-box modal-box" style="width: 500px;">
    <div class="page-header" style="margin-top: 0;">
      <span class="h4">Purchase</span>
    </div>
    <%= form_for [account, purchase], html: { class: 'form-horizontal' }, remote: true do |f| %>
      <div class="form-group required" style="margin-bottom: 20px;">
        <div class="col-sm-offset-3 col-sm-6">
          <%= f.text_field :amount, class: 'form-control', placeholder: 'Amount' %>
          <%= render 'shared/validation_error', model: purchase, attribute: :amount %>
        </div>
      </div>

      <span class="break-row"></span>

      <div class="row">
        <div class="col-sm-12" style="text-align: center;">
          <%= f.submit 'Buy', class: 'btn btn-primary' %>
          <button type="button" class="btn btn-default" onclick="$('.modal-wrapper').remove();">Cancel</button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/purchases/_list.html.erb
<% if purchases.present? %>
  <p style="margin: 0; font-style: italic;">Recent purchases:</p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Purchase</th>
      </tr>
    </thead>
    <tbody>
      <% purchases.each do |purchase| %>
        <tr>
          <td><%= purchase.created_at.strftime("%m/%d/%Y") %></td>
          <td>You bought <strong><%= number_to_currency(purchase.amount, precision: 0) %></strong> worth of goods</td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="text-alert">No Purchases.</p>
<% end %>

app/views/purchases/create.js.erb
if ($('.modal-wrapper').length) {
  $('.modal-wrapper').remove();
}

$('#points-balance').text("<%= @customer_account.points_balance %>");
$('#total-purchases').text("<%= number_to_currency(@customer_account.total_purchases, precision: 0) %>");

$('#purchase-list').html("<%= escape_javascript(render 'list', purchases: @last_purchases) %>");
$('#collapse_purchases').collapse('show');

app/views/purchases/new.js.erb
if ($('.modal-wrapper').length) {
  $('.modal-wrapper').remove();
}

$('body').prepend("<%= escape_javascript(render 'form', account: @customer_account, purchase: @purchase) %>");

app/views/rewards/_form.html.erb
<div class="modal-wrapper">
  <div class="inner-box modal-box" style="width: 500px;">
    <div class="page-header" style="margin-top: 0;">
      <span class="h4">Reward</span>
    </div>
    <%= form_for [account, reward], html: { class: 'form-horizontal' }, remote: true do |f| %>
      <div class="form-group required" style="margin-bottom: 20px;">
        <div class="col-sm-offset-3 col-sm-6">
          <%= f.text_field :points, class: 'form-control', placeholder: 'Points' %>
          <%= render 'shared/validation_error', model: reward, attribute: :points %>
        </div>
      </div>

      <span class="break-row"></span>

      <div class="row">
        <div class="col-sm-12" style="text-align: center;">
          <%= f.submit 'Redeem', class: 'btn btn-primary' %>
          <button type="button" class="btn btn-default" onclick="$('.modal-wrapper').remove();">Cancel</button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/rewards/_list.html.erb
<% if rewards.present? %>
  <p style="margin: 0; font-style: italic;">Recent rewards:</p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Reward</th>
      </tr>
    </thead>
    <tbody>
      <% rewards.each do |reward| %>
        <tr>
          <td><%= reward.created_at.strftime("%m/%d/%Y") %></td>
          <td>You got a reward for <strong><%= reward.points %></strong> points</td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="text-alert">No Rewards.</p>
<% end %>

app/views/rewards/create.js.erb
if ($('.modal-wrapper').length) {
  $('.modal-wrapper').remove();
}

$('#points-balance').text("<%= @customer_account.points_balance %>");

$('#reward-list').html("<%= escape_javascript(render 'list', rewards: @last_rewards) %>");
$('#collapse_rewards').collapse('show');

app/views/rewards/new.js.erb
if ($('.modal-wrapper').length) {
  $('.modal-wrapper').remove();
}

$('body').prepend("<%= escape_javascript(render 'form', account: @customer_account, reward: @reward) %>");

app/views/shared/_base_error.js.erb
$('body').prepend("<div class='modal-wrapper'><div class='inner-box modal-box' style='width: 500px;'><div class='row'><div class='col-sm-12'><p class='text-alert' style='margin-bottom: 20px; font-size: 15px;'><%= model.errors.messages[:base].join ', ' %>.</p></div></div><span class='break-row'></span><div class='row'><div class='col-sm-12' style='margin-top: 10px; text-align: center;'><button type='button' id='modal-ok' class='btn btn-default' style='color: red; border-color: red;'>OK</button></div></div></div></div>");

$('#modal-ok').on("click", function(e) {
  $('.modal-wrapper').remove();
});

app/views/shared/_validation_error.html.erb
<% if model.errors[attribute].any? %>
  <span class="form-validation-error"><em>
    <%= model.errors.messages[attribute].join ', ' %>.
  </em></span>
<% end %>